#include <spglib.h>

#include <CLI/CLI.hpp>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

#include "kpath.h"
#include "poscar_file.h"
#include "symmetry.h"

namespace {

// Find the KPoint entry by label (linear search — path tables are small).
const KPoint* findPoint(const KPath& kp, const std::string& label) {
    for (const auto& pt : kp.points)
        if (pt.label == label)
            return &pt;
    return nullptr;
}

bool writeKpoints(const KPath& kpath, int nkpts, const std::string& filename) {
    std::ofstream f(filename);
    if (!f) {
        std::cerr << "Error: cannot open " << filename << " for writing\n";
        return false;
    }

    f << "k-path generated by poscar_kpath (" << kpath.bravais_label << ")\n";
    f << nkpts << "\n";
    f << "Line_mode\n";
    f << "Reciprocal\n";

    const auto& segs = kpath.segments;
    for (size_t i = 0; i < segs.size(); ++i) {
        const KPoint* a = findPoint(kpath, segs[i].from);
        const KPoint* b = findPoint(kpath, segs[i].to);
        if (!a || !b) {
            std::cerr << "Error: unknown label in segment " << segs[i].from << "-" << segs[i].to << "\n";
            return false;
        }

        f << std::fixed << std::setprecision(10) << std::setw(14) << a->kx << " " << std::setw(14) << a->ky << " "
          << std::setw(14) << a->kz << "   ! " << a->label << "\n";
        f << std::fixed << std::setprecision(10) << std::setw(14) << b->kx << " " << std::setw(14) << b->ky << " "
          << std::setw(14) << b->kz << "   ! " << b->label << "\n";

        if (i + 1 < segs.size())
            f << "\n";
    }
    return true;
}

}  // namespace

int main(int argc, char* argv[]) {
    CLI::App app{"Generate VASP KPOINTS line-mode file from POSCAR using spglib"};

    std::string inputFile{"POSCAR"};
    std::string kpointsFile{"KPOINTS"};
    std::string primFile{"POSCAR_prim"};
    double symprec{1e-5};
    int nkpts{20};
    bool no_prim{false};

    app.add_option("--input,-i", inputFile, "Input POSCAR file")->capture_default_str()->check(CLI::ExistingFile);
    app.add_option("--output,-o", kpointsFile, "Output KPOINTS file")->capture_default_str();
    app.add_option("--prim", primFile, "Output primitive POSCAR file")->capture_default_str();
    app.add_option("--symprec", symprec, "Symmetry tolerance")->capture_default_str()->check(CLI::PositiveNumber);
    app.add_option("--nkpts,-n", nkpts, "Number of k-points per segment")
        ->capture_default_str()
        ->check(CLI::PositiveNumber);
    app.add_flag("--no-prim", no_prim, "Do not write the primitive cell POSCAR");

    CLI11_PARSE(app, argc, argv);

    POSCAR poscar;
    if (!poscar.readPOSCAR(inputFile)) {
        std::cerr << "Error: failed to read " << inputFile << "\n";
        return 1;
    }

    // Standardize to conventional cell for Bravais type detection.
    auto maybe_conv = standardizeCell(poscar, symprec, 0, 0);
    if (!maybe_conv) {
        std::cerr << "Error: spglib could not standardize the cell.\n";
        return 1;
    }

    // Primitive cell — needed for aP subcase detection (reciprocal angle orientation).
    auto maybe_prim_early = standardizeCell(poscar, symprec, 1, 0);
    if (!maybe_prim_early) {
        std::cerr << "Error: spglib could not generate primitive cell.\n";
        return 1;
    }

    auto dataset = analyzeSymmetry(*maybe_conv, symprec);
    if (!dataset) {
        std::cerr << "Error: spglib symmetry analysis failed.\n";
        return 1;
    }

    std::cout << "Space group: " << dataset->international_symbol << " (#" << dataset->spacegroup_number << ")\n";

    // Pass the input POSCAR (not spglib's re-standardized primitive) as the
    // orientation reference for aP (P-1) subcase detection.  spglib may choose
    // a different P-1 basis than pymatgen, which changes the reciprocal-angle
    // classification; the raw input cell matches the orientation that the user
    // (or pymatgen upstream) already committed to.
    auto maybe_kpath = getBravaisKPath(*maybe_conv, poscar, *dataset);
    if (!maybe_kpath) {
        std::cerr << "Error: Bravais lattice type not supported.\n"
                  << "  (international symbol: " << dataset->international_symbol << ")\n"
                  << "  Supported: cP cF cI  tP tI  oP oF oI oC  hP hR  mP mC  aP\n";
        return 1;
    }

    std::cout << "Bravais type: " << maybe_kpath->bravais_label << "\n";
    std::cout << "Segments: " << maybe_kpath->segments.size() << "  Special points: " << maybe_kpath->points.size()
              << "\n";

    if (!writeKpoints(*maybe_kpath, nkpts, kpointsFile))
        return 1;
    std::cout << "Written: " << kpointsFile << "\n";

    if (!no_prim) {
        if (!maybe_prim_early->writePOSCAR(primFile)) {
            std::cerr << "Warning: failed to write " << primFile << "\n";
        } else {
            std::cout << "Written: " << primFile << " (use this POSCAR for the band structure run)\n";
        }
    }

    return 0;
}
